/* This file was generated by SableCC (http://www.sablecc.org/). */

package nl.openedge.gaps.support.gapspath.lexer;

public class LexerException extends Exception {

    public LexerException(String message) {
        super(message);
    }
}