/* This file was generated by SableCC (http://www.sablecc.org/). */

package nl.openedge.gaps.support.berekeningen.node;

import nl.openedge.gaps.support.berekeningen.analysis.Analysis;

public final class ANumberExp extends PExp {

    private TNumber _number_;

    public ANumberExp() {
    }

    public ANumberExp(TNumber _number_) {
        setNumber(_number_);

    }

    public Object clone() {
        return new ANumberExp((TNumber) cloneNode(_number_));
    }

    public void apply(Switch sw) {
        ((Analysis) sw).caseANumberExp(this);
    }

    public TNumber getNumber() {
        return _number_;
    }

    public void setNumber(TNumber node) {
        if (_number_ != null) {
            _number_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _number_ = node;
    }

    public String toString() {
        return "" + toString(_number_);
    }

    void removeChild(Node child) {
        if (_number_ == child) {
            _number_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild) {
        if (_number_ == oldChild) {
            setNumber((TNumber) newChild);
            return;
        }

    }
}