/* This file was generated by SableCC (http://www.sablecc.org/). */

package nl.openedge.gaps.support.gapspath.node;

import nl.openedge.gaps.support.gapspath.analysis.Analysis;

public final class TMinus extends Token
{

	/**
	 * constuctor.
	 */
	public TMinus()
	{
		super.setText("-");
	}

	/**
	 * constuctor.
	 *
	 * @param line
	 * @param pos
	 */
	public TMinus(int line, int pos)
	{
		super.setText("-");
		setLine(line);
		setPos(pos);
	}

	/**
	 * @see nl.openedge.gaps.support.gapspath.node.Node#clone()
	 */
	public Object clone()
	{
		return new TMinus(getLine(), getPos());
	}

	/**
	 * @see nl.openedge.gaps.support.gapspath.node.Switchable#apply(nl.openedge.gaps.support.gapspath.node.Switch)
	 */
	public void apply(Switch sw)
	{
		((Analysis) sw).caseTMinus(this);
	}

	/**
	 * @see nl.openedge.gaps.support.gapspath.node.Token#setText(java.lang.String)
	 */
	public void setText(String text)
	{
		throw new RuntimeException("Cannot change TMinus text.");
	}
}