/* This file was generated by SableCC (http://www.sablecc.org/). */

package nl.openedge.gaps.support.gapspath.node;

import nl.openedge.gaps.support.gapspath.analysis.Analysis;

public final class TColon extends Token
{

	public TColon(String text)
	{
		setText(text);
	}

	public TColon(String text, int line, int pos)
	{
		setText(text);
		setLine(line);
		setPos(pos);
	}

	public Object clone()
	{
		return new TColon(getText(), getLine(), getPos());
	}

	public void apply(Switch sw)
	{
		((Analysis) sw).caseTColon(this);
	}
}