/* This file was generated by SableCC (http://www.sablecc.org/). */

package nl.openedge.gaps.support.gapspath.node;

import nl.openedge.gaps.support.gapspath.analysis.Analysis;

public final class TSlash extends Token
{

	public TSlash()
	{
		super.setText("/");
	}

	public TSlash(int line, int pos)
	{
		super.setText("/");
		setLine(line);
		setPos(pos);
	}

	public Object clone()
	{
		return new TSlash(getLine(), getPos());
	}

	public void apply(Switch sw)
	{
		((Analysis) sw).caseTSlash(this);
	}

	public void setText(String text)
	{
		throw new RuntimeException("Cannot change TSlash text.");
	}
}