/* This file was generated by SableCC (http://www.sablecc.org/). */

package nl.openedge.gaps.support.berekeningen.lexer;

public class LexerException extends Exception
{
    /** serial UUID. */
	private static final long serialVersionUID = 8711639022789962902L;

    public LexerException(String message)
	{
		super(message);
	}
}