/* This file was generated by SableCC (http://www.sablecc.org/). */

package nl.openedge.gaps.support.berekeningen.parser;

import nl.openedge.gaps.support.berekeningen.node.Token;

public class ParserException extends Exception
{

	Token token;

	public ParserException(Token token, String message)
	{
		super(message);
		this.token = token;
	}

	public Token getToken()
	{
		return token;
	}
}