/* This file was generated by SableCC (http://www.sablecc.org/). */

package nl.openedge.gaps.support.gapspath.node;

import nl.openedge.gaps.support.gapspath.analysis.Analysis;

public final class AParam extends PParam
{

	private TSlash _slash_;

	private TId _id_;

	private PArraySelect _arraySelect_;

	private PAttribute _attribute_;

	public AParam()
	{
	}

	public AParam(TSlash _slash_, TId _id_, PArraySelect _arraySelect_,
			PAttribute _attribute_)
	{
		setSlash(_slash_);

		setId(_id_);

		setArraySelect(_arraySelect_);

		setAttribute(_attribute_);

	}

	public Object clone()
	{
		return new AParam((TSlash) cloneNode(_slash_), (TId) cloneNode(_id_),
				(PArraySelect) cloneNode(_arraySelect_),
				(PAttribute) cloneNode(_attribute_));
	}

	public void apply(Switch sw)
	{
		((Analysis) sw).caseAParam(this);
	}

	public TSlash getSlash()
	{
		return _slash_;
	}

	public void setSlash(TSlash node)
	{
		if (_slash_ != null)
		{
			_slash_.parent(null);
		}

		if (node != null)
		{
			if (node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_slash_ = node;
	}

	public TId getId()
	{
		return _id_;
	}

	public void setId(TId node)
	{
		if (_id_ != null)
		{
			_id_.parent(null);
		}

		if (node != null)
		{
			if (node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_id_ = node;
	}

	public PArraySelect getArraySelect()
	{
		return _arraySelect_;
	}

	public void setArraySelect(PArraySelect node)
	{
		if (_arraySelect_ != null)
		{
			_arraySelect_.parent(null);
		}

		if (node != null)
		{
			if (node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_arraySelect_ = node;
	}

	public PAttribute getAttribute()
	{
		return _attribute_;
	}

	public void setAttribute(PAttribute node)
	{
		if (_attribute_ != null)
		{
			_attribute_.parent(null);
		}

		if (node != null)
		{
			if (node.parent() != null)
			{
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		_attribute_ = node;
	}

	public String toString()
	{
		return ""
				+ toString(_slash_) + toString(_id_) + toString(_arraySelect_)
				+ toString(_attribute_);
	}

	void removeChild(Node child)
	{
		if (_slash_ == child)
		{
			_slash_ = null;
			return;
		}

		if (_id_ == child)
		{
			_id_ = null;
			return;
		}

		if (_arraySelect_ == child)
		{
			_arraySelect_ = null;
			return;
		}

		if (_attribute_ == child)
		{
			_attribute_ = null;
			return;
		}

	}

	void replaceChild(Node oldChild, Node newChild)
	{
		if (_slash_ == oldChild)
		{
			setSlash((TSlash) newChild);
			return;
		}

		if (_id_ == oldChild)
		{
			setId((TId) newChild);
			return;
		}

		if (_arraySelect_ == oldChild)
		{
			setArraySelect((PArraySelect) newChild);
			return;
		}

		if (_attribute_ == oldChild)
		{
			setAttribute((PAttribute) newChild);
			return;
		}

	}
}